
## port 번호 설정
#server.port=9000
#server.servlet.context-path=/boot10
#server.servlet.session.tracking-modes=cookie
server:
  port: 9000
  servlet:
    context-path: /boot11
    session:
      tracking-modes: cookie

## oracle DataSource Setting ( Connection Pool )
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=scott
#spring.datasource.password=tiger

#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=60MB
spring:
 datasource:
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521:xe
   username: scott
   password: tiger
 servlet:
   multipart:
     max-file-size: 50MB
     max-request-size: 60MB
 
  




## mybatis 에서 사용하는 mapper xml 문서가 어디에 있는지 알려주기 classpath: 은 resources 폴더를 가리킨다 
#mybatis.mapper-locations=classpath:mapper/*.xml
## type alias scan setting @Alias 어노테이션이 붙은 클래스를 찾아서 사용할 준비
#mybatis.type-aliases-package=com.example.boot09.**

mybatis:
  mapper-locations: 
  - classpath:mapper/*.xml
  type-aliases-package: com.example.boot11.**
